### ISSUE TITLE
Is there a plan to clean up Tags on ROS Answers site?

### ISSUE THREAD

**Issue by kleucht** [ros-infrastructure/answers.ros.org#161]
Per http://answers.ros.org/question/271895/is-there-a-plan-to-clean-up-tags-on-ros-answers-site/

I'm not suggesting that it be a manual effort. There definitely should be an easy-button for admins to accomplish this task. and maybe eventually it could even be completely automated.

But I just earlier asked a Universal Robots question and the following three Tags were all available for me to use:

```
universal-robot 
universal-robots 
universal_robot
```

Not knowing which was the most popular choice, I chose to tag my post with all 3. Which is not ideal. For several reasons.

Is there an effort or a plan to reduce examples like this to a single commonly used Tag? It's website maintenance that would need to be done on a regular basis, because users will continue to make sloppy in-informed Tags.

> gvdhoorn answered:
> I don't know whether we are planning to do something like this, but it would definitely be a good idea (if only to get rid of all the tags that start with #: this is not twitter, and we don't use hashtags).   It would be nice if you could post an issue on ros-infrastructure/answers.ros.org, as your suggestion is really something that should be tracked there: your question will lose visibility after a while.

**Comment by 130s** [comment]
+1 I have the same frustration, as well as #134.

`#` issue mentioned btw must have been handled in https://github.com/ros-infrastructure/answers.ros.org/issues/54 (but do they still remain in suggestion drop down as mentioned there?).

**Comment by tfoote** [comment]
Answers.ros.org is an instance of ASKBOT we can deploy newer versions but these sort of feature requests need to be file upstream with that project and once they're released out we can deploy them.

There's two related issues upstream: 
https://github.com/ASKBOT/askbot-devel/issues/734
https://github.com/ASKBOT/askbot-devel/issues/564

And more suggestions would be appreciated.

Since the scope for resolving these requests is for the upstream project not our instance. I'm going to close this here.
