### ISSUE TITLE
enhancement:  Answers in comments don't get closed

### ISSUE THREAD

**Issue by droter** [ros-infrastructure/answers.ros.org#172]
Some open questions are actually answered in the comment section.  How do these get changed to answered?

Example:  https://answers.ros.org/question/263044/tf-frequency-is-too-large/

**Comment by 130s** [comment]
I see `convert to answer` link like the screenshot below taken from [the referenced thread](https://answers.ros.org/question/263044/tf-frequency-is-too-large/), but I'm a moderator so may not be the case for everyone.
![screenshot from 2018-06-22 10-28-57](https://user-images.githubusercontent.com/1840401/41790337-1a817c1c-7607-11e8-9fd9-e65535e7409d.png)

Since moderators are very active and meticulous, as long as the best "answer" in the comment sections is somehow made obvious, they will convert the comment into an answer (then mark it as a selected answer). That's at least what I do whenever I noticed. 

In the referenced case, however, I can't tell which one is the one that can be escalated. Upvoting comments sometimes helps.

**Comment by tfoote** [comment]
Yes, anyone with enough Karma can do that. If you have enough please do what @130s mentions.
