### ISSUE TITLE
"Unanswered" feature shows "Unresolved" questions?

### ISSUE THREAD

**Issue by 130s** [ros-infrastructure/answers.ros.org#175]
See https://answers.ros.org/questions/scope:unanswered/sort:answers-desc/page:1/

I see `unanswered` feature is on, AND questions that have some answers. They just look unresolved.
I just thought this is a bit confusing.

Also, is there a way to show questions that have no answers?

**Comment by tfoote** [comment]
There's a toggle to change whether "unanswered means unresolved or 0 answers" since the unresolved ones are the ones wanting attention I have the setting set to that. If you want to count questions with 0 answers I sort by number of answers and count how many tabinated pages in you have to go to get the number. It's manual but you don't need to do it too often.

![screenshot from 2018-09-18 17-32-50](https://user-images.githubusercontent.com/447804/45723996-04208380-bb69-11e8-97f7-42418df874bf.png)

**Comment by 130s** [comment]
> There's a toggle 

I assume that's admin's feature. Anyways all is clear. Thanks!

**Comment by tfoote** [comment]
Yeah, it's a site wide admin toggle.
