### ISSUE TITLE
Many new users keep posting despite the plan to move to stackexchange

### ISSUE THREAD

**Issue by 130s** [ros-infrastructure/answers.ros.org#220]
In spite of the announcement [discourse.ros.org#28068](https://discourse.ros.org/t/planned-migration-of-ros-answers-and-gazebo-answers-to-robotics-stack-exchange/28068), many new users are signing up on answers.ros.org https://github.com/ros-infrastructure/answers.ros.org/issues/210#issuecomment-1379086616. 

10+ new users in 4 hours is not trivial IMO. Those new users would soon have to move to a new website, which could lead to confusion. Moderation effort is felt kind of wasted too.

**Comment by 130s** [comment]
I totally understand the well-planned, full-featured migration would take time. In the meantime, is it a bad idea to notify at the new user registration that answers stackexchange is now a recommended Q/A forum? @tfoote

**Comment by tfoote** [comment]
We need to do the transition of everyone all at once. If we send all new users to the new site, but experienced users are on the old site they will have a bad experience.  We also want them to find the corpus of questions already asked instead of asking a duplicate question because they've been sent to a new site. 

For reference in the last 30 new users 8 are not spammers and that was in the last 14 hours. Looking at the recently asked question they have asked about 30% of the questions in that period. The site is still very active and working to help people. 

We don't want to stop people from getting help in the meantime and although new users will have to make the transition, they're likely to have an easier time to transition without having been ingrained as much in their habits etc. I'm going to close this as there's not much we can do to fix it. 

Please note that the moderation now is just as valuable as the moderation previously. If we don't have our moderators we'd have to stop the site basically as spammers would take over very quickly.

**Comment by ros-discourse** [comment]
This issue has been mentioned on **ROS Discourse**. There might be relevant details there:

https://discourse.ros.org/t/would-it-make-sense-to-migrate-ros-answers-to-stack-exchange/17123/11
