### ISSUE TITLE
verbatim code formatting broken when preceded by a list item  (ros ticket #3372)

### ISSUE THREAD

**Issue by tfoote** [ros-infrastructure/answers.ros.org#4]
This sort of text is very badly formatted:

{{{
- list item
  
  pre-formatted code text
  these lines should not run together
  (but they do)
  }}}

Without the list it works:

{{{
Normal paragraph of text.

```
pre-formatted code text
these lines should not run together
(now they work)
```

}}}

trac data:
- Owner: **mwise**
- Reporter: **joq**
- Reported at: **Fri Feb 25 14:08:17 2011**
- URL: https://code.ros.org/trac/ros/ticket/3372

**Comment by evgenyfadeev** [comment]
This is by design in Markdown. The indented block after the list item is interpreted as continuation of the previous list item.

It is possible to have code inside the list, however you'd need to "double-indent" by 8 chars. Rather obscure.

It is also trivial to just insert a paragraph such as "See code below", and then add the code block.
