### ISSUE TITLE
periodic emails appear to have stopped arriving

### ISSUE THREAD

**Issue by tfoote** [ros-infrastructure/answers.ros.org#46]
I was mistaken that the headings were present because I had not received new batched emails and was looking at old ones. 

The last email I got was July 20th

**Comment by evgenyfadeev** [comment]
We need to migrate to postgresql and then this will be fixed

**Comment by nuclearsandwich** [comment]
Bumping this because @mikaelarguedas and I noticed that we weren't getting the emails we were expecting and assumed everything was fine. At least for me, switching to instant delivery allows emails to come through.

This is not a high priority at the moment but maybe we can add it to an infrastructure sprint someday.

**Comment by tfoote** [comment]
I believe that this was resolved.

**Comment by mikaelarguedas** [comment]
I moved to direct notifications instead of batch emails so I cannot confirm this is fixed
