### ISSUE TITLE
answers.ros.org is slow tonight

### ISSUE THREAD

**Issue by trainman419** [ros-infrastructure/answers.ros.org#82]
It's taking me upwards of 20-30 seconds for the form submission for posting an answer to complete. I suspect other requests are taking a long time as well.

Is there anything the hosting provider can do to improve performance here? Perhaps more RAM or faster disks if we're hitting disk bottlenecks, or per-IP bandwidth limits if we're getting slammed by spiders?

**Comment by tfoote** [comment]
An event happened last night, that I"m not sure what it was that took the incoming bandwidth from typical 0.0X Mb/s to 88 Mb/s briefly.

![answer ros org_anomaly](https://cloud.githubusercontent.com/assets/447804/3261291/adb8e246-f257-11e3-8385-dff36c06235f.png)

It's not quite the same time. And there was some swap used at the time which is odd since it's only using 50% of physical memory at the moment.

There was also some issues overnight with other services at OSUOSL. I got several alerts on availability of packages.ros.org and download.ros.org and they show downtime here: http://status.ros.org/

It might have been an overall connectivity issue. The answers.ros.org load CPU and memory usage otherwise is doing well.  It's responsive right now and I can't find anything to look into besides that one traffic spike so I'll close.
